### ISSUE TITLE
Monitoring Swarms & Lightning nodes EPIC

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#177]
**Goal**

Improve reliability by increasing monitoring and alerts for Swarms, Lightning nodes and liquidity.

**Superadmin**

- [ ] Add healthcheck endpoints to each service
- [ ] Add ability to update swarms inside Superadmin

Payments & Liquidity

- [ ] Lightning nodes going down? (email? sms? Certain nodes)
- [ ] Alerts if channel gets hits a low balance threshold
- [ ] Automated channel refill if channel is closed or depleted
- [ ] Special attention to nodes with large tribes (alerts?)
- [ ] Easy way to refill channel
- [ ] Automated UTXO management?
