### ISSUE TITLE
Add `Restart` button to swarm UI

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#316]
**Task**

Add `Restart` button to swarm UI:

<img width="261" alt="Screenshot 2024-10-02 at 14 34 33" src="https://github.com/user-attachments/assets/14b6a474-0055-4436-ae7c-5a668db7026b">

Under the hood this should run this command:

./stop.sh
./restart-second-brain

This does the following:

1. Pulls the latest code or Docker image.
2. Stops and removes the running container (sphinx-swarm).
3. Uses Docker Compose to restart the sphinx-swarm service.
4. Tails the logs of the newly started container to show real-time output.

**Comment by tomsmith8** [comment]
At a per service level:

- [ ] Stop container of the service
- [ ] Remove it
- [ ] Restart it - do not pull recent image
  - [ ] Starts all pre-scripts
