### ISSUE TITLE
[Personal graph] Messaging 

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#323]
**Task**

Personal Graph Messaging:

- [ ] Create Person node
- [ ] Create link between Person -> Message
- [ ] Message threading
- [ ] Update Schema of a 'Message'
- [ ] Threading Messaging
- [ ] Edge between thread1->thread2
- [ ] Linking Person and Contacts

**Comment by tomsmith8** [comment]
@Evanfeenstra send me schema updates needed for support of all the threading / pubkeys etc.

Basically, anything that we could possible store for a message we can make optional

(we might even need a thread node)

**Comment by Evanfeenstra** [comment]
@tomsmith8 I added the last 5 attributes onto the schemas in our swarms. The final message format is:

```
{
"uuid": "string",
"content": "string",
"amount": "int",
"sender": "string",
"date": "int",
"reply": "?string",
"chat_pubkey": "?string",
"thread_uuid": "?string",
"media_token": "?string",
"media_key": "?string",
"media_type": "?string"
}
```

**Comment by tomsmith8** [comment]
@Evanfeenstra awesome thanks! I'll update the default schema going forward
