### ISSUE TITLE
[Lightning Payments] Tracking Issues

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#350]
- [ ] Unable to pay invoice on SB to bot server (v2)
  - [ ] Unable to send from v2 -> v1 (Point SB lightning node to a v2 node)
- [ ] Unable to send from v1 sphinx users to v2 sphinx user (swarm4 -> bot server)
- [ ] Unable to withdraw to nodes like Binance, Cashapp, Strike
